const facilitiesList = [
    {
        facilityImg: "https://mikazuki.com.vn/vnt_upload/product/08_2021/thumbs/1000__Deluxe___King_1.jpg",
        facilityName: "Deluxe Room",
        facilityArea: "Diện tích phòng: 85.8 m2",
        facilityRentalCost: "20000",
        facitilyMaxPeople: '5',
        facilityRentalType: 'Ngày',
        facilityTypeId: 1,
        facilityStandard: 'vip',
        facilityOtherAminities: 'Thuê xe máy / xe đạp',
        facilityPoolArea: '12',
        facilityNumbOfFloor: '3',
        facilityFreeAminities: null,
        facilityAminitiesid: [1, 2]
    },
   {
        facilityImg: "https://mikazuki.com.vn/vnt_upload/product/08_2021/thumbs/1000__Deluxe___King_1.jpg",
        facilityName: "Deluxe Room",
        facilityArea: "Diện tích phòng: 85.8 m2",
        facilityRentalCost: "20000",
        facitilyMaxPeople: '5',
        facilityRentalType: 'Ngày',
        facilityTypeId: 1,
        facilityStandard: 'vip',
        facilityOtherAminities: 'Thuê xe máy / xe đạp',
        facilityPoolArea: '12',
        facilityNumbOfFloor: '3',
        facilityFreeAminities: null,
        facilityAminitiesid: [1, 2]
    },
   {
        facilityImg: "https://mikazuki.com.vn/vnt_upload/product/08_2021/thumbs/1000__Deluxe___King_1.jpg",
        facilityName: "Deluxe Room",
        facilityArea: "Diện tích phòng: 85.8 m2",
        facilityRentalCost: "20000",
        facitilyMaxPeople: '5',
        facilityRentalType: 'Ngày',
        facilityTypeId: 1,
        facilityStandard: 'vip',
        facilityOtherAminities: 'Thuê xe máy / xe đạp',
        facilityPoolArea: '12',
        facilityNumbOfFloor: '3',
        facilityFreeAminities: null,
        facilityAminitiesid: [1, 2]
    },
   {
        facilityImg: "https://mikazuki.com.vn/vnt_upload/product/08_2021/thumbs/1000__Deluxe___King_1.jpg",
        facilityName: "Deluxe Room",
        facilityArea: "Diện tích phòng: 85.8 m2",
        facilityRentalCost: "20000",
        facitilyMaxPeople: '5',
        facilityRentalType: 'Ngày',
        facilityTypeId: 1,
        facilityStandard: 'vip',
        facilityOtherAminities: 'Thuê xe máy / xe đạp',
        facilityPoolArea: '12',
        facilityNumbOfFloor: '3',
        facilityFreeAminities: null,
        facilityAminitiesid: [1, 2]
    },
   {
        facilityImg: "https://mikazuki.com.vn/vnt_upload/product/08_2021/thumbs/1000__Deluxe___King_1.jpg",
        facilityName: "Deluxe Room",
        facilityArea: "Diện tích phòng: 85.8 m2",
        facilityRentalCost: "20000",
        facitilyMaxPeople: '5',
        facilityRentalType: 'Ngày',
        facilityTypeId: 1,
        facilityStandard: 'vip',
        facilityOtherAminities: 'Thuê xe máy / xe đạp',
        facilityPoolArea: '12',
        facilityNumbOfFloor: '3',
        facilityFreeAminities: null,
        facilityAminitiesid: [1, 2]
    },
   {
        facilityImg: "https://mikazuki.com.vn/vnt_upload/product/08_2021/thumbs/1000__Deluxe___King_1.jpg",
        facilityName: "Deluxe Room",
        facilityArea: "Diện tích phòng: 85.8 m2",
        facilityRentalCost: "20000",
        facitilyMaxPeople: '5',
        facilityRentalType: 'Ngày',
        facilityTypeId: 1,
        facilityStandard: 'vip',
        facilityOtherAminities: 'Thuê xe máy / xe đạp',
        facilityPoolArea: '12',
        facilityNumbOfFloor: '3',
        facilityFreeAminities: null,
        facilityAminitiesid: [1, 2]
    },

];

export default facilitiesList;